---
title: "p8105_hw5_rw3031"
author: "Polly Wu (rw3031)"
date: "2024-11-03"
output: github_document
---

```{r, include=FALSE, message = FALSE, Warning = FALSE}
library(tidyverse)
library(ggplot2)

knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)

```


# Problem 1

## simulation for birthday duplicate check

```{r}
birthday_dup = function(n){
 date_list = sample(1:365, n, replace = TRUE)
 
 dup_btd = any(duplicated(date_list))

 return(dup_btd)
}

birthday_sim_df=
expand_grid(
  n=c(2:50),
  iter = 1:10000)|>
  mutate(
    output = map(n,birthday_dup))|>
  unnest(output)
```

## compute the probabilty of birthday duplicates

```{r}
btd_dup_df=
birthday_sim_df|>
  group_by(n,output)|>
  summarise(count = n())|>
  pivot_wider(
    values_from = count,
    names_from = output,
    names_prefix = "count_"
  )|>
  rename(group_size=n)|>
  mutate(
    probability_of_dup = count_TRUE/10000
  )|>
  select(group_size,probability_of_dup)

btd_dup_df
```

## plot on relationship between sample size and probability of duplicates

```{r}
btd_dup_df|>
  ggplot(aes(x=group_size, y=probability_of_dup))+geom_point()+geom_smooth()+
  labs(x="group size", y="probability of duplicate birthdays")
```
The graph indicates that the group size is linearily associated with the log of the probability of duplication within birth dates. 

# Problem 2

```{r}
t_test = function(mu){
  
  n=30
  sigma = 5
  
  x=rnorm(n,mean=mu,sd=sigma)
  
  output = t.test(x,mu=0, conf.level = 0.95)|>
              broom::tidy()
  
  return(output)
}

t_test(0)
```


# Problem 3